resources:
  repositories:
  - repository: self
    type: git
    ref: main
jobs:
- job: Job_1
  displayName: Run Tosca
  pool:
    name: Hosted VS2017
  steps:
  - checkout: self
  - task: CmdLine@1
    displayName: Run ToscaCI Client
    inputs:
      filename: C:\agent\Client\ToscaCIClient.exe
      arguments: -m distributed -t junit -r results.xml -c conf-execution-list.xml -e http://toscademovm:90/distributionserverservice/managerservice.svc
  - task: PublishTestResults@2
    displayName: Publish Test Results
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/results*.xml'
...
